# Generated by Django 3.1.2 on 2021-04-12 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cidade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.cidade'),
        ),
        migrations.AddField(
            model_name='rota',
            name='cidade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.cidade'),
        ),
        migrations.AddField(
            model_name='rota',
            name='clientes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.cliente'),
        ),
        migrations.AddField(
            model_name='rota',
            name='funcionario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.funcionario'),
        ),
    ]
