# Generated by Django 3.1.2 on 2020-11-20 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='none', max_length=20)),
                ('description', models.CharField(default='none', max_length=20)),
                ('url', models.CharField(default='none', max_length=20)),
                ('area', models.CharField(choices=[('Geometria', 'Geometria'), ('Calculo', 'Cálculo'), ('Estatistica', 'Estatística'), ('Aritimetica', 'Aritimética'), ('Trigonometria', 'Trigonometria'), ('Algebra', 'Álgebra'), ('Probabilidade', 'Probabilidade'), ('Funcoes', 'Funções')], default='none', max_length=20)),
                ('language', models.CharField(choices=[('PT', 'Português'), ('EN', 'Ingles')], default='none', max_length=20)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Final', 'Final'), ('Unavailable', 'Unavailable')], default='none', max_length=20)),
                ('contribute', models.CharField(choices=[('Author', 'Author'), ('Unknown', 'Unknown'), ('Editor', 'Editor')], default='none', max_length=20)),
                ('location', models.CharField(choices=[('Geogebra', 'Geogebra'), ('Github', 'Github')], default='none', max_length=20)),
                ('interactivity_type', models.CharField(choices=[('Active', 'Active'), ('Expositive', 'Expositive'), ('Mixed', 'Mixed'), ('Undefined', 'Undefined')], default='none', max_length=20)),
                ('interactivity_resourse', models.CharField(choices=[('Simulation', 'Simulation'), ('Exercise', 'Exercise'), ('Experiment', 'Experiment')], default='none', max_length=20)),
                ('interactivity_level', models.CharField(choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high')], default='none', max_length=20)),
                ('context', models.CharField(choices=[('Primary', 'Primary'), ('Secondary', 'Secondary'), ('Higher', 'Higher'), ('University', 'University')], default='none', max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'easy'), ('medium', 'medium'), ('hard', 'hard')], default='none', max_length=20)),
                ('cost', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='none', max_length=20)),
                ('copyright', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='none', max_length=20)),
            ],
        ),
    ]
